name: Publish to PyPI (OIDC)

on:
  push:
    tags: ["v*.*.*"]
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # OIDC required

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build sdist/wheel
        run: |
          pipx install poetry
          poetry build
      - name: Twine check
        run: pipx run twine check dist/*
      - name: Publish via OIDC (no token)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hashes: true
          skip-existing: true
