name: Publish to PyPI (OIDC)

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build & twine
        run: python -m pip install -U build twine

      - name: Build sdist/wheel
        run: python -m build

      - name: Twine check
        run: python -m twine check dist/*

      - name: Publish via OIDC (no token)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          skip-existing: true
